# Generated by Django 4.1 on 2022-12-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewJournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='creationDate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
