# Generated by Django 4.1 on 2022-12-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewJournal', '0002_alter_journalentry_creationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
